<table border="0" cellpadding="0" cellspacing="0" width="653" style="border-collapse:collapse;width:491pt">

    <colgroup>
        <col width="135" style="width:101pt">
        <col width="97" style="width:73pt">
        <col width="126" span="2" style="width:95pt">
        <col width="169" style="width:127pt">
    </colgroup>
    <tbody>

        <tr height="21" style="height:15.75pt">
            <td height="21" style="height:15.75pt;color:white;font-weight:700;text-align:center;border-top:none;border-right:none;border-bottom:1pt solid rgb(69,77,85);border-left:1pt solid windowtext;background:rgb(52,58,64);padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Sector</td>
            <td style="color:white;font-weight:700;text-align:center;border-top:none;border-right:none;border-bottom:1pt solid rgb(69,77,85);border-left:none;background:rgb(52,58,64);padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Travel Date</td>
            <td style="color:white;font-weight:700;text-align:center;border-top:none;border-right:none;border-bottom:1pt solid rgb(69,77,85);border-left:none;background:rgb(52,58,64);padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">PNR</td>
            <td style="color:white;font-weight:700;text-align:center;border-top:none;border-right:none;border-bottom:1pt solid rgb(69,77,85);border-left:none;background:rgb(52,58,64);padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">No of Pax</td>
            <td style="color:white;font-weight:700;text-align:center;border-top:none;border-right:1pt solid windowtext;border-bottom:1pt solid rgb(69,77,85);border-left:none;background:rgb(52,58,64);padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap" colspan="2">Flight No</td>
        </tr>
        <tr height="21" style="height:15.75pt;box-sizing:border-box">
            <td height="21" style="height:15.75pt;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-top:1pt solid rgb(227,231,237);border-right:none;border-bottom:1pt solid windowtext;border-left:1pt solid windowtext;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">{{ $ticket_details->destination->name }}</td>
            <td style="box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-top:1pt solid rgb(227,231,237);border-right:none;border-bottom:1pt solid windowtext;border-left:none;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">{{ $ticket_details->travel_date->format('d-M-Y')}}</td>
            <td style="box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-top:1pt solid rgb(227,231,237);border-right:none;border-bottom:1pt solid windowtext;border-left:none;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">{{ $ticket_details->pnr }}</td>
            <td style="box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-top:1pt solid rgb(227,231,237);border-right:none;border-bottom:1pt solid windowtext;border-left:none;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">{{ $ticket_details->quantity }}</td>
            <td style="box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-top:1pt solid rgb(227,231,237);border-right:1pt solid windowtext;border-bottom:1pt solid windowtext;border-left:none;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap" colspan="2">{{ $ticket_details->flight_no }}</td>
        </tr>
        <tr height="21" style="height:15.75pt">
            <td height="21" style="height:15.75pt;color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
        </tr>
        <tr height="21" style="height:15.75pt">
            <td height="21" style="height:15.75pt;color:rgb(121,135,161);font-weight:700;text-align:center;border-width:1pt;border-style:solid;border-color:windowtext rgb(227,231,237) rgb(227,231,237) windowtext;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">#</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Title</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">First Name</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Last Name</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">TYPE</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid windowtext;border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">CONTACT NUMBER</td>
        </tr>
        @foreach($data as $key => $val)
        <tr height="21" style="height:15.75pt;box-sizing:border-box">
            <td height="21" style="height:15.75pt;border-top:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);border-left:1pt solid windowtext;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">{{ 1 +$key }}.</td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap"> {{ $val->title }} </td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap"> {{ $val->first_name }} </td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">{{ $val->last_name }} </td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap ">@if($val->type == 1)  Adult @else Child @endif </td>
            <td style="border-top:none;border-left:none;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid windowtext;border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;white-space:nowrap">{{ $val->agentPhone }} </td>
        </tr>

        @endforeach
      
        <tr height="21" style="height:15.75pt">
            <td height="21" style="height:15.75pt;color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
            <td style="color:rgb(28,39,60);text-align:center;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap">&nbsp;</td>
        </tr>
        <tr height="21" style="height:15.75pt">
            <td colspan="5" 
            style="color:rgb(28,39,60);text-align:left;vertical-align:middle;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;border:none;white-space:nowrap"
            >Infant Details</td>
        </tr>

        <tr height="21" style="height:15.75pt">
            <td height="21" style="height:15.75pt;color:rgb(121,135,161);font-weight:700;text-align:center;border-width:1pt;border-style:solid;border-color:windowtext rgb(227,231,237) rgb(227,231,237) windowtext;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">#</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Title</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">First Name</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Last Name</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">DOB</td>
            <td style="border-left:none;color:rgb(121,135,161);font-weight:700;text-align:center;border-top:1pt solid windowtext;border-right:1pt solid windowtext;border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;vertical-align:bottom;white-space:nowrap">Travelling With</td>
        </tr>
        
        @foreach($infant_details as $key2 => $infant)
        @if(isset($infant->title))

     
        <tr height="21" style="height:15.75pt;box-sizing:border-box">
            <td height="21" 
            style="height:15.75pt;border-top:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);border-left:1pt solid windowtext;background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">
            {{ 1 + $key2 }}.
            </td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap"> {{ $infant->title }} </td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">@if($infant) {{ $infant->first_name }} @endif</td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap">@if($infant){{ $infant->last_name }}@endif </td>
            <td style="border-top:none;border-left:none;box-sizing:border-box;padding:0.3rem;font-size:0.875rem;text-align:center;vertical-align:middle;border-right:1pt solid rgb(227,231,237);border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;font-family:Calibri,sans-serif;white-space:nowrap "> @if($infant->dob){{ $infant->dob->format('d-m-Y') }} @endif</td>
            <td style="border-top:none;border-left:none;color:rgb(28,39,60);text-align:center;vertical-align:middle;border-right:1pt solid windowtext;border-bottom:1pt solid rgb(227,231,237);background-image:initial;background-position:initial;background-size:initial;background-repeat:initial;background-origin:initial;background-clip:initial;padding-top:1px;padding-right:1px;padding-left:1px;font-size:11pt;font-family:Calibri,sans-serif;white-space:nowrap">@if($infant){{ $infant->travelling_with}} @endif</td>
        </tr>
        @endif
        
        @endforeach

        




    </tbody>
</table>
